name: npmjs.com

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli --version 0.2.85
      - name: Build wasm
        working-directory: ./bindings/js/wasm
        run: bash build-pkg.sh

      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - working-directory: ./bindings/js/example
        run: yarn install
      - working-directory: ./bindings/js/example
        run: yarn test

      - working-directory: ./bindings/js/wasm/pkg
        run: yarn install
      - working-directory: ./bindings/js/wasm/pkg
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
